version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7003:7003"
    volumes:
      - .:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
